version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
      - ./backend/cookies.txt:/app/cookies.txt

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
